class WrapperNotInstalledError(Exception): ...


class OptimizerError(Exception): ...


class ForceFieldSetupError(Exception): ...


class CalculatorError(Exception): ...


class DifferentAtomError(Exception): ...


class DifferentMoleculeError(Exception): ...


class ConversionError(Exception): ...


class ExpectedMetalError(Exception): ...


class PathError(Exception): ...


class ForceFieldError(Exception): ...


class LewisStructureError(Exception): ...


class InputError(Exception): ...


class InvalidSolventError(Exception): ...


class ConvergenceError(Exception): ...


class NotStartedError(Exception): ...


class NotCompletedError(Exception): ...


class SettingConflictError(Exception): ...


class NotDitopicThreeSiteError(Exception): ...
