name: Publish release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish-release:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/lukasturcani/stk-test-environment

    env:
      VERSION: ${{ github.ref_name }}

    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Add stk to the conda environment
        run: conda run -n stk
          pip install --no-deps -e .
      - name: Build stk
        run: conda run -n stk
          python -m build
      - name: Publish stk
        run: conda run -n stk
          twine upload
          -u ${{ secrets.PYPI_USERNAME }}
          -p ${{ secrets.PYPI_PASSWORD }}
          dist/*
